services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: simple_bank:1.0.0
    container_name: api

    ports:
      - "8080:8080"

    environment:
      HTTP_ADDR: :8080
      DATABASE_URL: postgres://admin:admin@postgres:5432/simple_bank?sslmode=disable

  postgres:
    image: postgres:18
    container_name: postgres

    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis

    volumes:
      - redis_data:/data

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: mq

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    restart: unless-stopped


volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: