-- +goose Up

--
-- CUSTOMERS
--

CREATE SEQUENCE customer_number_seq START WITH 10000000 INCREMENT BY 1;

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number BIGINT NOT NULL UNIQUE DEFAULT NEXTVAL('customer_number_seq'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
);

CREATE TYPE account_type AS ENUM ('current', 'savings');
CREATE TYPE account_status AS ENUM ('active', 'pending', 'closed');

--
-- DEVICES
--

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    device_id TEXT NOT NULL UNIQUE,
    device_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--
-- ACCOUNTS
--

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),

    account_type account_type NOT NULL,
    account_number TEXT NOT NULL UNIQUE,
    balance NUMERIC(19, 4) NOT NULL DEFAULT 0.00,
    status account_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_accounts_customer_id ON accounts(customer_id);

-- +goose Down
DROP TABLE accounts;
DROP TABLE devices;
DROP TABLE customers;

DROP TYPE account_type;
DROP TYPE account_status;
DROP SEQUENCE customer_number_seq;