-- +goose Up

--
-- CUSTOMERS
--

CREATE SEQUENCE customer_number_seq START WITH 10000000 INCREMENT BY 1;
CREATE TYPE customer_identity_type AS ENUM ('pesel');

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number BIGINT NOT NULL UNIQUE DEFAULT NEXTVAL('customer_number_seq'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,

    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    identity_type customer_identity_type NOT NULL DEFAULT 'pesel',
    identity_number TEXT NOT NULL UNIQUE
);

--
-- USERS
--

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    password_hash TEXT NOT NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_users_customer_id ON users(customer_id);

--
-- DEVICES
--

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),

    device_type TEXT NOT NULL,
    platform TEXT NOT NULL,
    trusted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_devices_user_id ON devices(user_id);

--
-- DEVICE PAIRING CODES
--

CREATE TABLE device_pairing_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES devices(id),

    code TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_device_pairing_codes_device_id ON device_pairing_codes(device_id);

--
-- ACCOUNTS
--

CREATE TYPE account_type AS ENUM ('current', 'savings');
CREATE TYPE account_status AS ENUM ('active', 'pending', 'closed');

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),

    account_type account_type NOT NULL,
    account_number TEXT NOT NULL UNIQUE,
    balance NUMERIC(19, 4) NOT NULL DEFAULT 0.00,
    status account_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opened_at TIMESTAMPTZ NULL,
    closed_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_accounts_user_id ON accounts(user_id);

-- +goose Down
DROP TABLE accounts;
DROP TABLE device_pairing_codes;
DROP TABLE devices;
DROP TABLE users;
DROP TABLE customers;

DROP TYPE customer_identity_type;
DROP TYPE account_type;
DROP TYPE account_status;
DROP SEQUENCE customer_number_seq;
